### PR TITLE
Add new hostconfig file on Lassen with Clang 14.

### PR DESCRIPTION
**Pull request by tpatki**
Adds a new hostconfig with the `-flegacy-pass-manager` flag.

### CODE REVIEW

**Comment by tpatki** [comment]
Hi @alizalisan : When you get a chance tomorrow, could you test this for me on Lassen? I have tested it at my end and it works correctly, but would like another pair of eyes on it.

**Comment by alizalisan** [comment]
@tpatki : Works on my end too! :)

**Comment by tpatki** [comment]
Thank you for testing @alizalisan ! I'll figure out why the checks are failing and then merge.

**Comment by tpatki** [comment]
Merging as the CI issue is not related to the PR.

**Pull request merged**
