### PR TITLE
Add .gitignore file

### PR DESCRIPTION
**Pull request by slabasan**

### CODE REVIEW

**Review by dongahn — APPROVED** [review]
LGTM!

**Comment by dongahn** [comment]
@slabasan: I just merged PR #30. Could you see if you need to rebase this to have a clean linear commit history? If so, please rebase and force a push. 

I think we should also add mergefyio support to help automate things like this. 

```
git fetch upstream #if upstream is your name for the upstream main branch
git rebase upstream/master
git push -f origin add-gitignore
```

**Comment by slabasan** [comment]
I'm not as familiar with mergifyio, but we can use the rebase and merge button as part of the pull requests to have a linear history.

**Comment by dongahn** [comment]
OK. I will do that. Please see https://github.com/flux-framework/flux-sched/blob/master/.mergify.yml which integrate [mergifyio](https://mergify.com) to fluxion as an example.

**Pull request merged**
